[build]
  command = "ng build"
  functions = "./functions"
  publish = "dist/angular-sw-web-notification"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 301
[[headers]]
    for = "/*"
        [headers.values]
            Cache-Control = "max-age=31536000"
            X-Content-Type-Options = "DENY"
            Content-Security-Policy = "default-src *  data: blob: filesystem: about: ws: wss: 'unsafe-inline' 'unsafe-eval'; script-src * data: blob: 'unsafe-inline' 'unsafe-eval'; connect-src * data: blob: 'unsafe-inline'; img-src * data: blob: 'unsafe-inline'; frame-src * data: blob: ; style-src * data: blob: 'unsafe-inline'; font-src * data: blob: 'unsafe-inline';"
            X-Frame-Options = "SAMEORIGIN"
            X-XSS-Protection = "1; mode=block"
